FROM node:12.16.1-alpine
LABEL maintainer="morteza.alizadeh@gmail.com"

ARG COVERALLS_SERVICE_NAME
ARG COVERALLS_REPO_TOKEN

ADD . /src
WORKDIR /src
RUN npm install
RUN npm run relay
RUN npm run test:ci
