FROM node:12.3.0
LABEL maintainer="morteza.alizadeh@gmail.com"

ARG COVERALLS_SERVICE_NAME
ARG COVERALLS_REPO_TOKEN

ADD . /src
WORKDIR /src
RUN make dep
RUN make relay
RUN make test-and-publish-results
