FROM node:14.15.4-alpine
LABEL maintainer="morteza.alizadeh@gmail.com"

ARG COVERALLS_SERVICE_NAME
ARG COVERALLS_REPO_TOKEN

ADD . /src
WORKDIR /src
RUN yarn install
RUN yarn run relay
RUN yarn run test:ci
